///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test_21657
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Test_21657Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("85685e61-e451-457b-b0eb-612b479d035b")]
    public partial class Test_21657Repository : RepoGenBaseFolder
    {
        static Test_21657Repository instance = new Test_21657Repository();

        /// <summary>
        /// Gets the singleton class instance representing the Test_21657Repository element repository.
        /// </summary>
        [RepositoryFolder("85685e61-e451-457b-b0eb-612b479d035b")]
        public static Test_21657Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Test_21657Repository() 
            : base("Test_21657Repository", "/", null, 0, false, "85685e61-e451-457b-b0eb-612b479d035b", ".\\RepositoryImages\\Test_21657Repository85685e61.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("85685e61-e451-457b-b0eb-612b479d035b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Test_21657RepositoryFolders
    {
    }
#pragma warning restore 0436
}
